name: Build Installer for Windows, Mac, Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller requests

    - name: Build installer
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          pyinstaller --onefile --noconsole --name=2898_Scouter_Installer installer.py
          mv dist/2898_Scouter_Installer.exe dist/2898_Scouter_Installer.exe
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          pyinstaller --onefile --noconsole --name=2898_Scouter_Installer installer.py
          mv dist/2898_Scouter_Installer dist/2898_Scouter_Installer.dmg
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          pyinstaller --onefile --noconsole --name=2898_Scouter_Installer installer.py
          mv dist/2898_Scouter_Installer dist/2898_Scouter_Installer.tar.gz
        fi

    - name: Upload the installer
      uses: actions/upload-artifact@v3
      with:
        name: 2898_Scouter_Installer-${{ matrix.os }}
        path: dist/
