name: Build Installer for Windows, Mac, Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pyinstaller requests
      shell: bash

    - name: Build installer
      shell: bash
      run: |
        pyinstaller --onefile --name=2898_Scouter_Installer installer.py

    - name: Rename artifacts for platform
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mv dist/2898_Scouter_Installer.exe dist/2898_Scouter_Installer-Windows.exe
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          zip -r dist/2898_Scouter_Installer-Mac.zip dist/2898_Scouter_Installer
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          tar -czvf dist/2898_Scouter_Installer-Linux.tar.gz -C dist/2898_Scouter_Installer
        fi

    - name: Upload the installer
      uses: actions/upload-artifact@v4
      with:
        name: 2898_Scouter_Installer-${{ runner.os }}
        path: dist/*
